# This workflow is used to run the unittest of pyiron

name: Unittests-openmpi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        python-version: ['3.11']
        include:
        - operating-system: macos-latest
          python-version: '3.11'
          label: osx-64-py-3-11
          prefix: /Users/runner/miniconda3/envs/my-env
          
        - operating-system: ubuntu-latest
          python-version: '3.11'
          label: linux-64-py-3-11
          prefix: /usr/share/miniconda3/envs/my-env
          
        - operating-system: ubuntu-latest
          python-version: '3.10'
          label: linux-64-py-3-10
          prefix: /usr/share/miniconda3/envs/my-env
          
        - operating-system: ubuntu-latest
          python-version: 3.9
          label: linux-64-py-3-9
          prefix: /usr/share/miniconda3/envs/my-env
          
        - operating-system: ubuntu-latest
          python-version: 3.8
          label: linux-64-py-3-8
          prefix: /usr/share/miniconda3/envs/my-env

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        miniforge-variant: Mambaforge
        channel-priority: strict
        auto-update-conda: true
        environment-file: .ci_support/environment-openmpi.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: coverage run --omit pympipool/_version.py -m unittest discover tests
      env:
        OMPI_MCA_plm: 'isolated'
        OMPI_MCA_rmaps_base_oversubscribe: 'yes'
        OMPI_MCA_btl_vader_single_copy_mechanism: 'none'
    - name: Coverage
      if:  matrix.label == 'linux-64-py-3-10'
      continue-on-error: True
      shell: bash -l {0}
      run: |
        coverage combine
        coveralls
        coverage xml
